// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.De.Facturacion.Web.Data;

namespace Sistema.De.Facturacion.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200605044604_iniciadb0")]
    partial class iniciadb0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("StateId");

                    b.HasKey("CityId");

                    b.HasIndex("StateId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("CountryId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Customer", b =>
                {
                    b.Property<int>("Customer_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoC")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Correo")
                        .IsRequired();

                    b.Property<string>("DireccionC")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ID_Doc");

                    b.Property<string>("NombreC")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("TelefonC")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("Customer_Id");

                    b.HasIndex("ID_Doc");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Document", b =>
                {
                    b.Property<int>("ID_Doc")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID_Doc");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Employee", b =>
                {
                    b.Property<int>("Employe_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cellphone")
                        .HasMaxLength(20);

                    b.Property<string>("Codigo_Empleado");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("Employee_Lastname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Employee_Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Extension")
                        .HasMaxLength(6);

                    b.Property<DateTime>("Fecha_Ingreso");

                    b.Property<int>("ID_Doc");

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<int>("Position_Id");

                    b.Property<bool>("Status");

                    b.HasKey("Employe_Id");

                    b.HasIndex("ID_Doc");

                    b.HasIndex("Position_Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Neighborhood", b =>
                {
                    b.Property<int>("NeighborhoodId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<string>("NeighborhoodName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("NeighborhoodId");

                    b.HasIndex("CityId");

                    b.ToTable("Neighborhood");
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Position", b =>
                {
                    b.Property<int>("Position_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Position_Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Position_Id");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("StateId");

                    b.HasIndex("CountryId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.City", b =>
                {
                    b.HasOne("Sistema.De.Facturacion.Web.Models.State", "States")
                        .WithMany("Citys")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Customer", b =>
                {
                    b.HasOne("Sistema.De.Facturacion.Web.Models.Document", "Documents")
                        .WithMany("Customers")
                        .HasForeignKey("ID_Doc")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Employee", b =>
                {
                    b.HasOne("Sistema.De.Facturacion.Web.Models.Document", "Documents")
                        .WithMany("Employees")
                        .HasForeignKey("ID_Doc")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sistema.De.Facturacion.Web.Models.Position", "position")
                        .WithMany("Employees")
                        .HasForeignKey("Position_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Neighborhood", b =>
                {
                    b.HasOne("Sistema.De.Facturacion.Web.Models.City", "Citys")
                        .WithMany("Neighborhoods")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.State", b =>
                {
                    b.HasOne("Sistema.De.Facturacion.Web.Models.Country", "Countrys")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
