// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.De.Facturacion.Web.Data;

namespace Sistema.De.Facturacion.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Customer", b =>
                {
                    b.Property<int>("Customer_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoC")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Correo")
                        .IsRequired();

                    b.Property<string>("DireccionC")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ID_Doc");

                    b.Property<string>("NombreC")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("TelefonC")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("Customer_Id");

                    b.HasIndex("ID_Doc");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Document", b =>
                {
                    b.Property<int>("ID_Doc")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID_Doc");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Employee", b =>
                {
                    b.Property<int>("Employe_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cellphone")
                        .HasMaxLength(20);

                    b.Property<int>("Codigo_Empleado");

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("Employee_Lastname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Employee_Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Extension")
                        .HasMaxLength(6);

                    b.Property<DateTime>("Fecha_Ingreso");

                    b.Property<int>("ID_Doc");

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<int>("Position_Id");

                    b.Property<bool>("Status");

                    b.HasKey("Employe_Id");

                    b.HasIndex("ID_Doc");

                    b.HasIndex("Position_Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Position", b =>
                {
                    b.Property<int>("Position_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Position_Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Position_Id");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Customer", b =>
                {
                    b.HasOne("Sistema.De.Facturacion.Web.Models.Document", "Documents")
                        .WithMany("Customers")
                        .HasForeignKey("ID_Doc")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sistema.De.Facturacion.Web.Models.Employee", b =>
                {
                    b.HasOne("Sistema.De.Facturacion.Web.Models.Document", "Document")
                        .WithMany("Employees")
                        .HasForeignKey("ID_Doc")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sistema.De.Facturacion.Web.Models.Position", "position")
                        .WithMany("Employees")
                        .HasForeignKey("Position_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
